package models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import models.converter.ListConverterForPost;

import java.util.LinkedList;
import java.util.List;


@Data
@DynamoDBTable(tableName = "post_thread")
public class PostThread {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private List<Post> posts;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBTypeConverted(converter = ListConverterForPost.class)
    public List<Post> getPosts() {
        return new LinkedList<>(posts);
    }

    public void setPosts(List<Post> posts) {
        this.posts = posts;
    }

    public void addPost(Post post) {
        posts.add(post);
    }

    public Post getPost(int index) {
       return posts.get(index);
    }


}
