package models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import lombok.Data;

import java.util.ArrayList;


@Data
public class PostThread {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private ArrayList<Post> posts;



    public PostThread(String id, String title, ArrayList<Post> posts) {
        this.id = id;
        this.title = title;
        this.posts = posts;
    }
    

    public void addPost(Post post) {
        posts.add(post);
    }

    public Post getPost(int index) {
       return posts.get(index);
    }


}
