package models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.LinkedList;

@Data
@AllArgsConstructor
@DynamoDBTable(tableName = "user")
public class Users {

    @DynamoDBAutoGeneratedKey
    private int id;

    private String username;

    private String password;

    private UserType type;

    private String bio;

    private ArrayList<Post> posts;

    private LinkedList<Wine> favorites;

    public Users() {
    }

    public Users(String username, String password) {
        this.username = username;
        this.password = password;
        this.type = UserType.USER;
        this.bio = "";
        posts = new ArrayList<>();
        favorites = new LinkedList<>();

    }


    @DynamoDBAttribute
    public UserType getType() {
        return type;
    }

    public void setType(UserType type) {
        this.type = type;
    }

    @DynamoDBHashKey
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }


    @DynamoDBAttribute
    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    @DynamoDBAttribute
    public ArrayList<Post> getPosts() {
        return posts;
    }

    public void setPosts(ArrayList<Post> posts) {
        this.posts = posts;
    }

    @DynamoDBAttribute
    public LinkedList<Wine> getFavorites() {
        return favorites;
    }

    public void setFavorites(LinkedList<Wine> favorites) {
        this.favorites = favorites;
    }

    public boolean addToFavorites(Wine wine) {
      return favorites.add(wine);
    }

    public void setUsername(String username) {
        this.username = username;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    @DynamoDBAttribute
    public String getUsername() {
        return this.username;
    }

    @DynamoDBAttribute
    public String getPassword() {
        return this.password;
    }

    @Override
    public String toString() {
        return "Users {" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", type=" + type +
                ", bio='" + bio + '\'' +
                ", posts=" + posts +
                ", favorites=" + favorites +
                '}';
    }
}
